[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/api/store"
  to = "/.netlify/functions/store"
  status = 200

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin-session"
  to = "/.netlify/functions/admin-session"
  status = 200

[[redirects]]
  from = "/api/admin-logout"
  to = "/.netlify/functions/admin-logout"
  status = 200

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/api/order"
  to = "/.netlify/functions/order"
  status = 200
